"""
Empirical comparison via the assignment-allowed route: structured literature summary.

Regenerated by main.py; aligns with reduced-form VAR/LP and IV-LP in empirical.py.
"""
from __future__ import annotations

from pathlib import Path


def write_literature_summary(outdir: Path) -> Path:
    """Plain-text summary for graders (reproducible without data download)."""
    text = """Literature-based fiscal evidence (qualitative; magnitudes vary by identification)

1) Blanchard & Perotti (QJE 2002) — quarterly VAR with institutional timing restrictions.
   Government spending innovations often raise output; private consumption and investment
   responses are sensitive to specification and ordering.

2) Ramey (QJE 2011) — narrative / timing identification for defense news.
   Emphasizes anticipation and can differ sharply from recursive fiscal VARs.

3) Auerbach & Gorodnichenko (AEJ: Policy 2012) — state-dependent fiscal multipliers.
   Recessions vs expansions: larger multipliers in slack states than narrow productivity-gap
   RBC calibrations typically generate.

Mapping to this project (code outputs):
- Model: Markov RBC solved by value iteration on (k,z) with continuous labor conditional on k';
  fiscal IRFs are Monte Carlo means over future z paths (rational expectations over Pi).
- Reduced-form data: Cholesky VAR and VAR-residual local projections (empirical_*.png, lp_irf_*.csv).
- Identified-style data: IV local projections with a predetermined lag of G as instrument
  (empirical_iv_lp.png, iv_lp_*.csv); weaker than narrative shocks but transparent.

Distortionary labor-tax extension (PF auxiliary) illustrates Ricardian failure when wedges break
neutrality; see report Section on extensions.
"""
    outdir.mkdir(parents=True, exist_ok=True)
    p = outdir / "literature_fiscal_summary.txt"
    p.write_text(text, encoding="utf-8")
    return p
